### ISSUE TITLE
Bases In Wrong Domain

### ISSUE THREAD

**Issue by DNAcer** [404Wolf/NATuG#11]
Sometimes bases appear in the incorrect domain. see attached picture.
<img width="1440" alt="Screen Shot 2022-12-05 at 11 50 57 PM" src="https://user-images.githubusercontent.com/118033291/205819079-bfb29714-3bac-49a1-b7c8-da750559c6f7.png">

**Comment by 404Wolf** [comment]
@DNAcer The problem has been resolved. The issue was that when it increased the angle the NEMid to create a nucleoside it didn't remodulo the angle. Fairly simple fix.
