### ISSUE TITLE
Separate Top View and Helix Graph Updates

### ISSUE THREAD

**Issue by DNAcer** [404Wolf/NATuG#3]
When you are manipulating the top view, particularly of a large tube, it is very time consuming to wait for the computer to generate the entire helix graph every time you update the graphs. Instead, we should have a button to just update the top view, or to automatically update just the top view. That would probably be very quick - certainly 100 quicker than making the helix graph.

Also we might want to switch the tab order on the Domains window to jump from one m value to the next when we're in autoupdate topview mode, and perhaps to switch the tab order to horizontal when we're in autoupdate helix graph mode.

**Comment by 404Wolf** [comment]
Part 1 has been implemented into /main; I'll look into part 2 later this week.

**Comment by 404Wolf** [comment]
Note to self about part 2:
For QTableWidget KeyStrokeEvent override if event.button == Qt.Buttons.Tab to move to next item down

**Comment by 404Wolf** [comment]
Second part of issue has been implemented.
